name: LocalSoundTouch
description: Custom Bose SoundTouch & UPnP controller with NAS playback
version: "1.0.0"
slug: localsoundtouch
init: false
arch:
  - aarch64
  - armhf
  - armv7
  - amd64
  - i386
startup: application
boot: auto
host_network: true
options:
  nas_host: "192.168.1.3"
  nas_share: "volume1"
  nas_username: "admin"
  nas_password: ""
schema:
  nas_host: str
  nas_share: str
  nas_username: str
  nas_password: str
